"#version 330\n"
"\n"
"// Input vertex attributes (from vertex shader)\n"
"in vec2 fragTexCoord;\n"
"in vec4 fragColor;\n"
"out vec4 finalColor;\n"
"\n"
"// Input uniform values\n"
"uniform sampler2D texture0;\n"
"uniform vec4 colDiffuse;\n"
"uniform vec2 resolution;\n"
"\n"
"#define CURVATURE 1.0\n"
"#define curve_amount 0.15\n"
"#define cornersize 0.05\n"
"#define DOTMASK 0.3\n"
"#define scanline_weight 0.3\n"
"\n"
"#define TEX2D(c) texture(texture0, (c))\n"
"\n"
"vec2 simple_warp(vec2 pos)\n"
"{\n"
"    pos = pos * 2.0 - 1.0;\n"
"    pos *= vec2(1.0 + (pos.y * pos.y) * (curve_amount * 0.2),\n"
"                1.0 + (pos.x * pos.x) * (curve_amount * 0.3));\n"
"    return pos * 0.5 + 0.5;\n"
"}\n"
"\n"
"vec4 scanlineWeights(float distance, vec4 color)\n"
"{\n"
"    float wid = 0.3 + 0.1 * dot(color.rgb, vec3(0.3, 0.6, 0.1));\n"
"    float w = distance / wid;\n"
"    return vec4((0.1 + scanline_weight) * exp(-w * w) / wid);\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    vec2 ilfac = vec2(1.0, clamp(floor(resolution.y / 200.0), 1.0, 2.0));\n"
"    vec2 ilvec = vec2(0.0);\n"
"    vec2 one = ilfac / resolution;\n"
"    float mod_factor = fragTexCoord.x * resolution.x;\n"
"\n"
"    vec2 xy = (CURVATURE > 0.5) ? simple_warp(fragTexCoord) : fragTexCoord;\n"
"\n"
"    vec2 corn = min(xy, 1.0 - xy);\n"
"    if (CURVATURE > 0.5) {\n"
"        corn.x = (cornersize * 0.001) / corn.x;\n"
"    }\n"
"\n"
"    if (xy.y < 0.0 || xy.y > 1.0 || xy.x < 0.0 || xy.x > 1.0) {\n"
"        finalColor = vec4(0.0);\n"
"        return;\n"
"    }\n"
"\n"
"    vec2 ratio_scale = (xy * resolution - vec2(0.5) + ilvec) / ilfac;\n"
"    vec2 uv_ratio = fract(ratio_scale);\n"
"    xy = (floor(ratio_scale) * ilfac + vec2(0.5) - ilvec) / resolution;\n"
"\n"
"    float FF = uv_ratio.x * uv_ratio.x;\n"
"    vec4 lobes = vec4(FF * uv_ratio.x, FF, uv_ratio.x, 1.0);\n"
"    vec4 InvX;\n"
"    InvX.x = dot(vec4(-0.5,  1.0, -0.5, 0.0), lobes);\n"
"    InvX.y = dot(vec4( 1.5, -2.5,  0.0, 1.0), lobes);\n"
"    InvX.z = dot(vec4(-1.5,  2.0,  0.5, 0.0), lobes);\n"
"    InvX.w = dot(vec4( 0.5, -0.5,  0.0, 0.0), lobes);\n"
"\n"
"    vec4 col  = mat4(TEX2D(xy + vec2(-one.x, 0.0)),\n"
"                     TEX2D(xy),\n"
"                     TEX2D(xy + vec2(one.x, 0.0)),\n"
"                     TEX2D(xy + vec2(2.0 * one.x, 0.0))) * InvX;\n"
"\n"
"    vec4 col2 = mat4(TEX2D(xy + vec2(-one.x, one.y)),\n"
"                     TEX2D(xy + vec2(0.0, one.y)),\n"
"                     TEX2D(xy + one),\n"
"                     TEX2D(xy + vec2(2.0 * one.x, one.y))) * InvX;\n"
"\n"
"    vec4 weights  = scanlineWeights(uv_ratio.y, col);\n"
"    vec4 weights2 = scanlineWeights(1.0 - uv_ratio.y, col2);\n"
"\n"
"    vec3 res = (col * weights + col2 * weights2).rgb;\n"
"\n"
"    vec3 dotMask = mix(vec3(1.0, 1.0 - DOTMASK, 1.0),\n"
"                       vec3(1.0 - DOTMASK, 1.0, 1.0 - DOTMASK),\n"
"                       floor(mod(mod_factor, 2.0)));\n"
"    res *= dotMask;\n"
"\n"
"    res = sqrt(clamp(res, 0.0, 1.0));\n"
"\n"
"    if ((CURVATURE > 0.5 && corn.y <= corn.x) || corn.x < 0.00001) res = vec3(0.0);\n"
"\n"
"    finalColor = vec4(res, 1.0);\n"
"}\n"
""
