"#version 120\n"
"varying vec2 fragTexCoord;\n"
"varying vec4 fragColor;\n"
"uniform sampler2D texture0;\n"
"uniform float saturation;\n"
"uniform vec3 tintColor;\n"
"uniform vec3 lumaWeights;\n"
"void main() {\n"
"    vec4 texColor = texture2D(texture0, fragTexCoord);\n"
"    float luma = dot(texColor.rgb, lumaWeights);\n"
"    vec3 gray = vec3(luma) * tintColor;\n"
"    gl_FragColor = vec4(mix(gray, texColor.rgb, saturation), texColor.a) * fragColor;\n"
"}"
