"#version 330\n"
"in vec2 fragTexCoord;\n"
"in vec4 fragColor;\n"
"out vec4 finalColor;\n"
"uniform sampler2D texture0;\n"
"uniform float saturation;\n"
"uniform vec3 tintColor;\n"
"uniform vec3 lumaWeights;\n"
"void main() {\n"
"    vec4 texColor = texture(texture0, fragTexCoord);\n"
"    float luma = dot(texColor.rgb, lumaWeights);\n"
"    vec3 gray = vec3(luma) * tintColor;\n"
"    finalColor = vec4(mix(gray, texColor.rgb, saturation), texColor.a) * fragColor;\n"
"}"
