"#version 120\n"
"varying vec2 fragTexCoord;\n"
"varying vec4 fragColor;\n"
"uniform sampler2D texture0;\n"
"uniform float chromaBleed;\n"
"uniform float noiseAmount;\n"
"uniform float dotCrawlSpeed;\n"
"uniform float sharpness;\n"
"uniform float time;\n"
"uniform vec2 resolution;\n"
"float rand(vec2 co) {\n"
"    return fract(sin(dot(co, vec2(12.9898, 78.233))) * 43758.5453);\n"
"}\n"
"void main() {\n"
"    vec2 ts = 1.0 / resolution;\n"
"    vec4 color = texture2D(texture0, fragTexCoord);\n"
"    vec4 bleed = texture2D(texture0, fragTexCoord + vec2(chromaBleed, 0.0));\n"
"    color.r = mix(color.r, bleed.r, 0.5);\n"
"    color.b = mix(color.b, bleed.b, 0.3);\n"
"    float crawl = sin(fragTexCoord.x * resolution.x * 3.14159 + time * dotCrawlSpeed * 6.28318) * 0.015;\n"
"    color.rgb += texture2D(texture0, fragTexCoord + vec2(crawl, 0.0)).rgb * 0.04;\n"
"    float noise = (rand(fragTexCoord + fract(vec2(time, time * 0.7))) - 0.5) * noiseAmount;\n"
"    color.rgb += vec3(noise);\n"
"    vec3 blur = (texture2D(texture0, fragTexCoord - vec2(ts.x, 0.0)).rgb +\n"
"                 texture2D(texture0, fragTexCoord + vec2(ts.x, 0.0)).rgb) * 0.5;\n"
"    color.rgb += (color.rgb - blur) * sharpness;\n"
"    gl_FragColor = clamp(color, 0.0, 1.0) * fragColor;\n"
"}"
