"#version 330\n"
"in vec2 fragTexCoord;\n"
"in vec4 fragColor;\n"
"out vec4 finalColor;\n"
"uniform sampler2D texture0;\n"
"uniform float frequency;\n"
"uniform float opacity;\n"
"uniform float offset;\n"
"uniform float time;\n"
"void main() {\n"
"    float globalPos = (fragTexCoord.y + offset) * frequency;\n"
"    float wavePos = cos((fract(globalPos) - 0.5) * 3.14159);\n"
"    vec4 texelColor = texture(texture0, fragTexCoord);\n"
"    finalColor = mix(texelColor * (1.0 - opacity), texelColor, wavePos) * fragColor;\n"
"}"
