"#version 120\n"
"varying vec2 fragTexCoord;\n"
"varying vec4 fragColor;\n"
"uniform sampler2D texture0;\n"
"uniform float frequency;\n"
"uniform float opacity;\n"
"uniform float offset;\n"
"uniform float time;\n"
"void main() {\n"
"    float globalPos = (fragTexCoord.y + offset) * frequency;\n"
"    float wavePos = cos((fract(globalPos) - 0.5) * 3.14159);\n"
"    vec4 texelColor = texture2D(texture0, fragTexCoord);\n"
"    gl_FragColor = mix(texelColor * (1.0 - opacity), texelColor, wavePos) * fragColor;\n"
"}"
