name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Update Packages
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install xorg-dev libglu1-mesa-dev -y
    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE=Debug -B build .
    - name: Build
      run: cmake --build build

  # build-web:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       submodules: recursive
  #   - name: Install Emscripten
  #     uses: mymindstorm/setup-emsdk@v14
  #   - name: Configure
  #     run: emcmake cmake -DPLATFORM=Web -DCMAKE_BUILD_TYPE=Release -B build .
  #   - name: Build
  #     run: cmake --build build

  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       submodules: recursive
  #   - name: Configure
  #     run: cmake -DCMAKE_BUILD_TYPE=Debug -B build .
  #   - name: Build
  #     run: cmake --build build
